# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devmon.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(11, 15, 461, 341))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 461, 297))
        self.page.setObjectName("page")
        self.device_ip = QtWidgets.QLabel(self.page)
        self.device_ip.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.device_ip.setTextFormat(QtCore.Qt.RichText)
        self.device_ip.setObjectName("device_ip")
        self.device_ip_entry = QtWidgets.QLineEdit(self.page)
        self.device_ip_entry.setGeometry(QtCore.QRect(100, 10, 141, 20))
        self.device_ip_entry.setObjectName("device_ip_entry")
        self.model_ssh_combobox = QtWidgets.QComboBox(self.page)
        self.model_ssh_combobox.setGeometry(QtCore.QRect(100, 100, 141, 22))
        self.model_ssh_combobox.setObjectName("model_ssh_combobox")
        self.model_ssh_combobox.addItem("")
        self.model_ssh_combobox.addItem("")
        self.model_ssh_combobox.addItem("")
        self.username_ssh = QtWidgets.QLabel(self.page)
        self.username_ssh.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.username_ssh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.username_ssh.setTextFormat(QtCore.Qt.RichText)
        self.username_ssh.setObjectName("username_ssh")
        self.username_ssh_entry = QtWidgets.QLineEdit(self.page)
        self.username_ssh_entry.setGeometry(QtCore.QRect(100, 40, 141, 20))
        self.username_ssh_entry.setObjectName("username_ssh_entry")
        self.password_ssh_entry = QtWidgets.QLineEdit(self.page)
        self.password_ssh_entry.setGeometry(QtCore.QRect(100, 70, 141, 20))
        self.password_ssh_entry.setObjectName("password_ssh_entry")
        self.password_ssh = QtWidgets.QLabel(self.page)
        self.password_ssh.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.password_ssh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.password_ssh.setTextFormat(QtCore.Qt.RichText)
        self.password_ssh.setObjectName("password_ssh")
        self.model_ssh = QtWidgets.QLabel(self.page)
        self.model_ssh.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.model_ssh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.model_ssh.setTextFormat(QtCore.Qt.RichText)
        self.model_ssh.setObjectName("model_ssh")
        self.purpose_ssh_combobox = QtWidgets.QComboBox(self.page)
        self.purpose_ssh_combobox.setGeometry(QtCore.QRect(100, 130, 141, 22))
        self.purpose_ssh_combobox.setObjectName("purpose_ssh_combobox")
        self.purpose_ssh_combobox.addItem("")
        self.purpose_ssh = QtWidgets.QLabel(self.page)
        self.purpose_ssh.setGeometry(QtCore.QRect(10, 130, 81, 21))
        self.purpose_ssh.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.purpose_ssh.setTextFormat(QtCore.Qt.RichText)
        self.purpose_ssh.setObjectName("purpose_ssh")
        self.go_ssh_button = QtWidgets.QPushButton(self.page)
        self.go_ssh_button.setGeometry(QtCore.QRect(100, 160, 141, 21))
        self.go_ssh_button.setObjectName("go_ssh_button")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 461, 297))
        self.page_2.setObjectName("page_2")
        self.purpose_console = QtWidgets.QLabel(self.page_2)
        self.purpose_console.setGeometry(QtCore.QRect(10, 190, 91, 21))
        self.purpose_console.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.purpose_console.setTextFormat(QtCore.Qt.RichText)
        self.purpose_console.setObjectName("purpose_console")
        self.baud_rate = QtWidgets.QLabel(self.page_2)
        self.baud_rate.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.baud_rate.setTextFormat(QtCore.Qt.RichText)
        self.baud_rate.setObjectName("baud_rate")
        self.username_console_entry = QtWidgets.QLineEdit(self.page_2)
        self.username_console_entry.setGeometry(QtCore.QRect(110, 70, 131, 20))
        self.username_console_entry.setObjectName("username_console_entry")
        self.com_port_console_entry = QtWidgets.QLineEdit(self.page_2)
        self.com_port_console_entry.setGeometry(QtCore.QRect(110, 40, 131, 20))
        self.com_port_console_entry.setObjectName("com_port_console_entry")
        self.com_port = QtWidgets.QLabel(self.page_2)
        self.com_port.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.com_port.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.com_port.setTextFormat(QtCore.Qt.RichText)
        self.com_port.setObjectName("com_port")
        self.model_console_combobox = QtWidgets.QComboBox(self.page_2)
        self.model_console_combobox.setGeometry(QtCore.QRect(110, 160, 131, 22))
        self.model_console_combobox.setObjectName("model_console_combobox")
        self.model_console_combobox.addItem("")
        self.model_console_combobox.addItem("")
        self.model_console_combobox.addItem("")
        self.go_console_button = QtWidgets.QPushButton(self.page_2)
        self.go_console_button.setGeometry(QtCore.QRect(110, 220, 131, 21))
        self.go_console_button.setObjectName("go_console_button")
        self.purpose_console_combobox = QtWidgets.QComboBox(self.page_2)
        self.purpose_console_combobox.setGeometry(QtCore.QRect(110, 190, 131, 22))
        self.purpose_console_combobox.setObjectName("purpose_console_combobox")
        self.purpose_console_combobox.addItem("")
        self.baud_rate_console_entry = QtWidgets.QLineEdit(self.page_2)
        self.baud_rate_console_entry.setGeometry(QtCore.QRect(110, 10, 131, 20))
        self.baud_rate_console_entry.setObjectName("baud_rate_console_entry")
        self.model_console = QtWidgets.QLabel(self.page_2)
        self.model_console.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.model_console.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.model_console.setTextFormat(QtCore.Qt.RichText)
        self.model_console.setObjectName("model_console")
        self.username_console = QtWidgets.QLabel(self.page_2)
        self.username_console.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.username_console.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.username_console.setTextFormat(QtCore.Qt.RichText)
        self.username_console.setObjectName("username_console")
        self.password_console = QtWidgets.QLabel(self.page_2)
        self.password_console.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.password_console.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.password_console.setTextFormat(QtCore.Qt.RichText)
        self.password_console.setObjectName("password_console")
        self.password_console_entry = QtWidgets.QLineEdit(self.page_2)
        self.password_console_entry.setGeometry(QtCore.QRect(110, 100, 131, 20))
        self.password_console_entry.setObjectName("password_console_entry")
        self.enable_console_entry = QtWidgets.QLineEdit(self.page_2)
        self.enable_console_entry.setGeometry(QtCore.QRect(110, 130, 131, 20))
        self.enable_console_entry.setObjectName("enable_console_entry")
        self.enable_console = QtWidgets.QLabel(self.page_2)
        self.enable_console.setGeometry(QtCore.QRect(10, 130, 91, 21))
        self.enable_console.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.enable_console.setTextFormat(QtCore.Qt.RichText)
        self.enable_console.setObjectName("enable_console")
        self.toolBox.addItem(self.page_2, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.toolButton = QtWidgets.QToolButton(self.tab_2)
        self.toolButton.setGeometry(QtCore.QRect(150, 20, 21, 21))
        self.toolButton.setObjectName("toolButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DevMon"))
        self.device_ip.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Device IP: </span></p></body></html>"))
        self.model_ssh_combobox.setItemText(0, _translate("MainWindow", "cisco_ios"))
        self.model_ssh_combobox.setItemText(1, _translate("MainWindow", "cisco_asa"))
        self.model_ssh_combobox.setItemText(2, _translate("MainWindow", "fortinet"))
        self.username_ssh.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Username: </span></p></body></html>"))
        self.password_ssh.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Password: </span></p></body></html>"))
        self.model_ssh.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Device Model: </span></p></body></html>"))
        self.purpose_ssh_combobox.setItemText(0, _translate("MainWindow", "Basic Troubleshooting"))
        self.purpose_ssh.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Purpose: </span></p></body></html>"))
        self.go_ssh_button.setText(_translate("MainWindow", "GO"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "via SSH/TELNET"))
        self.purpose_console.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Purpose: </span></p></body></html>"))
        self.baud_rate.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Baud Rate: </span></p></body></html>"))
        self.com_port.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">COM Port: </span></p></body></html>"))
        self.model_console_combobox.setItemText(0, _translate("MainWindow", "cisco_ios"))
        self.model_console_combobox.setItemText(1, _translate("MainWindow", "cisco_asa"))
        self.model_console_combobox.setItemText(2, _translate("MainWindow", "fortinet"))
        self.go_console_button.setText(_translate("MainWindow", "GO"))
        self.purpose_console_combobox.setItemText(0, _translate("MainWindow", "Basic Troubleshooting"))
        self.model_console.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Device Model: </span></p></body></html>"))
        self.username_console.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Username: </span></p></body></html>"))
        self.password_console.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Password: </span></p></body></html>"))
        self.enable_console.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Enable Secret: </span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "via CONSOLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Single Device"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Select the file: </span></p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Multiple Device"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())